// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Ventas.Modeling.Models;

namespace Ventas.Modeling.Models
{
    public partial interface ISalesContextProcedures
    {
        Task<int> GuardarProductoAsync(string CodigoBarra, string Marca, string Descripcion, int? IdCategoria, int? Stock, string UrlImagen, string NombreImagen, decimal? Precio, int? IdUsuarioCreacion, OutputParameter<string> p_result, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateProductoAsync(string CodigoBarra, string Marca, string Descripcion, int? IdCategoria, int? Stock, string UrlImagen, string NombreImagen, decimal? Precio, int? Id, int? IdUsuarioMod, OutputParameter<string> p_result, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
